version: "3.8"
services:
    nginx:
        container_name: ${APP_NAME}_nginx
        build:
            context: ./docker/nginx
        ports:
            - "80:80"
            - "443:443"
        working_dir: /app
        depends_on:
            - php
        volumes:
            - ./:/app
    php:
        container_name: ${APP_NAME}_php
        build:
            context: ./docker/php
        ports:
            - "9000:9000"
        working_dir: /app
        volumes:
            - ./:/app

    postgres:
      image: postgres:15.0-alpine
      container_name: ${APP_NAME}_postgres
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
      ports:
        - "5432:5432"
      volumes:
        - ./docker/.data/postgres:/var/lib/postgresql/data
